version: '3.5'

services:
  mongodb-backend:
    #
    restart: always
    image: mongo:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    # environment:
    #   - PORT=${PORT}
    ports:
      - '3000:3000'
    # depends_on:
    #   - db
    volumes:
      - ./src:/app/src

